table 'Location Table'
	lineageTag: ef695584-9d0b-4bbf-a5ae-14b2a7663290

	column LocationID
		dataType: int64
		formatString: 0
		lineageTag: 1583e7f5-5096-4de7-8029-5c47a8c04cd1
		summarizeBy: none
		sourceColumn: LocationID

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Location
		dataType: string
		lineageTag: a9f8f665-dc4d-4d61-9771-6c3cc2d17a0a
		summarizeBy: none
		sourceColumn: Location

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column City
		dataType: string
		lineageTag: 40144c0c-6a12-4d2f-aed4-4692a3a0e635
		summarizeBy: none
		sourceColumn: City

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	partition 'Location Table' = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(File.Contents("F:\power bi\uber_analysis\Location Table.xlsx"), null, true),
				    #"Location Table_Sheet" = Source{[Item="Location Table",Kind="Sheet"]}[Data],
				    #"Promoted Headers" = Table.PromoteHeaders(#"Location Table_Sheet", [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"LocationID", Int64.Type}, {"Location", type text}, {"City", type text}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

